# Generated by Django 5.1.1 on 2024-10-26 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_alter_movie_janre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='actor',
            field=models.ManyToManyField(to='movie.actor'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='country',
            field=models.ManyToManyField(to='movie.country'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.ManyToManyField(to='movie.directory'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='janre',
            field=models.ManyToManyField(to='movie.janre'),
        ),
    ]
